### get All Person
GET http://localhost:3000/person

### get Person With Id
GET http://localhost:3000/person/2


### create person
POST http://localhost:3000/person
Content-Type: application/json

{
  "firstName": "farhang",
  "lastName": "ezziirani",
  "email": "farhang.ezziirani@gmail.com",
  "nationalCode": "0079131001",
  "address": "tehran",
  "mobile": "09126034368",
  "idno": "2860",
  "fatherName": "abbas"
}

### update person
PUT http://localhost:3000/person/2
Content-Type: application/json

{
  "firstName": "nahid"
}

###delete person
DELETE http://localhost:3000/person/2