### get All Person
GET http://localhost:3000/person

### get Person With Id
GET http://localhost:3000/person/3


### create person
POST http://localhost:3000/person
Content-Type: application/json

{
  "firstName": "فرهنگ",
  "lastName": "عزی ایرانی",
  "email": "farhang.ezziirani@gmail.com",
  "nationalCode": "0079131001",
  "address": "تهران شهرک ژاندارمری",
  "mobile": "09126034368",
  "idno": "2865",
  "fatherName": "عباس",
  "gender": 2
}

### update person
PUT http://localhost:3000/person/3
Content-Type: application/json

{
  "gender": 2
}

###delete person
DELETE http://localhost:3000/person/1